/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Control.ControlCategoria;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.Categoria;

/**
 *
 * @author Luis
 */
public class FrmCategorias extends javax.swing.JFrame {

    private ControlCategoria controlCategoria;

    public FrmCategorias() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        controlCategoria = new ControlCategoria();
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetallesCategoria = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTablaCategorias = new javax.swing.JLabel();
        paneCategorias = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        provedoresOption = new javax.swing.JMenuItem();
        productosOption = new javax.swing.JMenuItem();
        categoriasOption = new javax.swing.JMenuItem();
        clientesOption = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        registrarVentaOption = new javax.swing.JMenuItem();
        busquedaVentaOption = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categorias");

        lblDetallesCategoria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDetallesCategoria.setText("Detalles Categoria");

        lblNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblDescripcion.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcion);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblTablaCategorias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTablaCategorias.setText("Tabla de Categorias");

        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCategorias);

        paneCategorias.add(jScrollPane2);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        txtID.setEditable(false);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\opcionesIcon.png")); // NOI18N
        jMenu1.setText("Opciones");

        provedoresOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\provedorIcon.png")); // NOI18N
        provedoresOption.setText("Provedores");
        provedoresOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provedoresOptionActionPerformed(evt);
            }
        });
        jMenu1.add(provedoresOption);

        productosOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\productoIcon.png")); // NOI18N
        productosOption.setText("Productos");
        productosOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosOptionActionPerformed(evt);
            }
        });
        jMenu1.add(productosOption);

        categoriasOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\categoriaIcon.png")); // NOI18N
        categoriasOption.setText("Categorias");
        categoriasOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasOptionActionPerformed(evt);
            }
        });
        jMenu1.add(categoriasOption);

        clientesOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\clienteIcon.png")); // NOI18N
        clientesOption.setText("Clientes");
        clientesOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesOptionActionPerformed(evt);
            }
        });
        jMenu1.add(clientesOption);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\ventaMenuBarMenuIcon.png")); // NOI18N
        jMenu3.setText("Ventas");

        registrarVentaOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\ventaIcon.png")); // NOI18N
        registrarVentaOption.setText("Registrar Venta");
        registrarVentaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentaOptionActionPerformed(evt);
            }
        });
        jMenu3.add(registrarVentaOption);

        busquedaVentaOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\consultarVentaIcon.png")); // NOI18N
        busquedaVentaOption.setText("Busqueda Venta");
        busquedaVentaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaVentaOptionActionPerformed(evt);
            }
        });
        jMenu3.add(busquedaVentaOption);

        jMenu1.add(jMenu3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\salirIcon.png")); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\aboutIcon.png")); // NOI18N
        jMenu2.setText("Acerca de");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblDetallesCategoria)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblDescripcion)
                                    .addComponent(jLabel1))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTablaCategorias)
                        .addGap(0, 330, Short.MAX_VALUE))
                    .addComponent(paneCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblDetallesCategoria))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTablaCategorias)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(btnSeleccionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.eliminarCategoria();
        this.cargarCategorias();
        this.limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.actualizarCategoria();
        this.cargarCategorias();
        this.limpiarFormulario();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        this.cargarCategoriaForm();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.insertarCategoria();
        this.limpiarFormulario();
        this.cargarCategorias();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.cargarCategorias();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        this.limitarCaracteres(txtNombre, evt, 45);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped

    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        this.limitarCaracteres(txtBuscar, evt, 45);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void provedoresOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provedoresOptionActionPerformed
        FrmProvedores frmProvedores = new FrmProvedores();
        frmProvedores.setVisible(true);
        dispose();
    }//GEN-LAST:event_provedoresOptionActionPerformed

    private void productosOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosOptionActionPerformed
        FrmProducto frmProductos = new FrmProducto();
        frmProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_productosOptionActionPerformed

    private void categoriasOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasOptionActionPerformed
        FrmCategorias frmCategorias = new FrmCategorias();
        frmCategorias.setVisible(true);
        dispose();
    }//GEN-LAST:event_categoriasOptionActionPerformed

    private void clientesOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesOptionActionPerformed
        FrmClientes frmClientes = new FrmClientes();
        frmClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesOptionActionPerformed

    private void registrarVentaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentaOptionActionPerformed
        FrmRegistroVentas frmRegistroVenta = new FrmRegistroVentas();
        frmRegistroVenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarVentaOptionActionPerformed

    private void busquedaVentaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaVentaOptionActionPerformed
        FrmBusquedaVentas frmBusquedaVenta = new FrmBusquedaVentas();
        frmBusquedaVenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_busquedaVentaOptionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JOptionPane.showMessageDialog(this, "Alumno: Daniel Alejandro Ornelas\nID: 00000192937", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCategorias().setVisible(true);
            }
        });
    }

    private void limitarCaracteres(javax.swing.JTextField textField, java.awt.event.KeyEvent evt, int longitud) {
        if (textField.getText().length() >= longitud) {
            evt.consume();
        }
    }

    private void cargarCategoriaForm() {
        int fila = this.tableCategorias.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una categoria ", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tableCategorias.getModel();
            int idCategoria = (int) modelo.getValueAt(fila, 0);
            Categoria categoria = controlCategoria.consultarCategoria(idCategoria);
            if (categoria != null) {
                txtID.setText(String.valueOf(categoria.getId()));
                txtNombre.setText(categoria.getNombre());
                txtDescripcion.setText(categoria.getDescripcion());
            }
        }
    }

    private void cargarCategorias() {

        List<Categoria> categorias = this.controlCategoria.consultarCategorias(txtBuscar.getText());
        if (categorias != null) {
            DefaultTableModel modelo = (DefaultTableModel) tableCategorias.getModel();
            modelo.setRowCount(0);
            for (Categoria categoria : categorias) {
                modelo.addRow(categoria.toArray());
            }
        }
    }

    private void insertarCategoria() {
        if (!txtNombre.getText().equals("") && !txtDescripcion.getText().equals("") && txtID.getText().equals("")) {
            Categoria categoria = new Categoria();
            categoria.setNombre(txtNombre.getText());
            categoria.setDescripcion(txtDescripcion.getText());
            controlCategoria.insertarCategoria(categoria);
        }
    }

    private void actualizarCategoria() {
        if (!txtNombre.getText().equals("") && !txtDescripcion.getText().equals("") && !txtID.getText().equals("")) {
            Categoria categoria = new Categoria();
            categoria.setId(Integer.parseInt(txtID.getText()));
            categoria.setNombre(txtNombre.getText());
            categoria.setDescripcion(txtDescripcion.getText());
            controlCategoria.actualizarCategoria(categoria);
        }

    }

    private void eliminarCategoria() {
        int fila = tableCategorias.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una categoria ", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tableCategorias.getModel();
            Integer idCategoria = (Integer) modelo.getValueAt(fila, 0);
            boolean eliminado = this.controlCategoria.eliminarCategoria(idCategoria);
            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Se elimino la categoria correctamente!", "Eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la categoria", "Eliminación fallida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtBuscar.setText("");
        txtID.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JMenuItem busquedaVentaOption;
    private javax.swing.JMenuItem categoriasOption;
    private javax.swing.JMenuItem clientesOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDetallesCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTablaCategorias;
    private java.awt.ScrollPane paneCategorias;
    private javax.swing.JMenuItem productosOption;
    private javax.swing.JMenuItem provedoresOption;
    private javax.swing.JMenuItem registrarVentaOption;
    private javax.swing.JTable tableCategorias;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
