/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Control.ControlCliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.Cliente;

/**
 *
 * @author Luis
 */
public class FrmClientes extends javax.swing.JFrame {

    ControlCliente controlCliente;

    public FrmClientes() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        controlCliente = new ControlCliente();
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClientes = new javax.swing.JLabel();
        lblRFC = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        lblTelefono2 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTablaClientes = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        paneClientes = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        provedoresOption = new javax.swing.JMenuItem();
        productosOption = new javax.swing.JMenuItem();
        categoriasOption = new javax.swing.JMenuItem();
        clientesOption = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        registrarVentaOption = new javax.swing.JMenuItem();
        busquedaVentaOption = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");

        lblClientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientes.setText("Detalles Clientes");

        lblRFC.setText("RFC:");

        txtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCActionPerformed(evt);
            }
        });
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });

        lblNombre.setText("Nombre:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblDireccion.setText("Dirección:");

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        lblTelefono1.setText("Telefono 1:");

        txtTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono1KeyTyped(evt);
            }
        });

        lblTelefono2.setText("Telefono 2:");

        txtTelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono2KeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTablaClientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTablaClientes.setText("Tabla de Clientes");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RFC", "Nombre", "Dirección", "Telefono 1", "Telefono 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        paneClientes.add(jScrollPane1);

        jLabel1.setText("ID:");

        txtID.setEditable(false);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\opcionesIcon.png")); // NOI18N
        jMenu1.setText("Opciones");

        provedoresOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\provedorIcon.png")); // NOI18N
        provedoresOption.setText("Provedores");
        provedoresOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provedoresOptionActionPerformed(evt);
            }
        });
        jMenu1.add(provedoresOption);

        productosOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\productoIcon.png")); // NOI18N
        productosOption.setText("Productos");
        productosOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosOptionActionPerformed(evt);
            }
        });
        jMenu1.add(productosOption);

        categoriasOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\categoriaIcon.png")); // NOI18N
        categoriasOption.setText("Categorias");
        categoriasOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasOptionActionPerformed(evt);
            }
        });
        jMenu1.add(categoriasOption);

        clientesOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\clienteIcon.png")); // NOI18N
        clientesOption.setText("Clientes");
        clientesOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesOptionActionPerformed(evt);
            }
        });
        jMenu1.add(clientesOption);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\ventaMenuBarMenuIcon.png")); // NOI18N
        jMenu3.setText("Ventas");

        registrarVentaOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\ventaIcon.png")); // NOI18N
        registrarVentaOption.setText("Registrar Venta");
        registrarVentaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentaOptionActionPerformed(evt);
            }
        });
        jMenu3.add(registrarVentaOption);

        busquedaVentaOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\consultarVentaIcon.png")); // NOI18N
        busquedaVentaOption.setText("Busqueda Venta");
        busquedaVentaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaVentaOptionActionPerformed(evt);
            }
        });
        jMenu3.add(busquedaVentaOption);

        jMenu1.add(jMenu3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\salirIcon.png")); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Desktop\\Proyecto02_00000192937\\img\\aboutIcon.png")); // NOI18N
        jMenu2.setText("Acerca de");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClientes)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTelefono2)
                                .addComponent(btnGuardar))
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefono2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEliminar)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRFC)
                                .addComponent(lblNombre)
                                .addComponent(lblDireccion)
                                .addComponent(lblTelefono1)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDireccion)
                                .addComponent(txtNombre)
                                .addComponent(txtRFC)
                                .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTablaClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSeleccionar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientes)
                    .addComponent(lblTablaClientes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(btnSeleccionar))
                        .addGap(8, 8, 8)
                        .addComponent(paneClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRFC)
                            .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono1)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono2)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.insertarCliente();
        this.limpiarFormulario();
        this.cargarClientes();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.eliminarCliente();
        this.cargarClientes();
        this.limpiarFormulario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        this.cargarClienteForm();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.actualizarCliente();
        this.cargarClientes();
        this.limpiarFormulario();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.cargarClientes();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono1KeyTyped
        this.validarNumerico(evt);
        this.limitarCaracteres(txtTelefono1, evt, 15);
    }//GEN-LAST:event_txtTelefono1KeyTyped

    private void txtTelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono2KeyTyped
        this.validarNumerico(evt);
        this.limitarCaracteres(txtTelefono2, evt, 15);
    }//GEN-LAST:event_txtTelefono2KeyTyped

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        this.limitarCaracteres(txtRFC, evt, 15);
    }//GEN-LAST:event_txtRFCKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        this.limitarCaracteres(txtNombre, evt, 45);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        this.limitarCaracteres(txtDireccion, evt, 100);
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        this.limitarCaracteres(txtBuscar, evt, 45);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void provedoresOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provedoresOptionActionPerformed
        FrmProvedores frmProvedores = new FrmProvedores();
        frmProvedores.setVisible(true);
        dispose();
    }//GEN-LAST:event_provedoresOptionActionPerformed

    private void productosOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosOptionActionPerformed
        FrmProducto frmProductos = new FrmProducto();
        frmProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_productosOptionActionPerformed

    private void categoriasOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasOptionActionPerformed
        FrmCategorias frmCategorias = new FrmCategorias();
        frmCategorias.setVisible(true);
        dispose();
    }//GEN-LAST:event_categoriasOptionActionPerformed

    private void clientesOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesOptionActionPerformed
        FrmClientes frmClientes = new FrmClientes();
        frmClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesOptionActionPerformed

    private void registrarVentaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentaOptionActionPerformed
        FrmRegistroVentas frmRegistroVenta = new FrmRegistroVentas();
        frmRegistroVenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarVentaOptionActionPerformed

    private void busquedaVentaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaVentaOptionActionPerformed
        FrmBusquedaVentas frmBusquedaVenta = new FrmBusquedaVentas();
        frmBusquedaVenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_busquedaVentaOptionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JOptionPane.showMessageDialog(this, "Alumno: Daniel Alejandro Ornelas\nID: 00000192937", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    private void limitarCaracteres(javax.swing.JTextField textField, java.awt.event.KeyEvent evt, int longitud) {
        if (textField.getText().length() >= longitud) {
            evt.consume();
        }
    }

    private void validarNumerico(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
        }
    }

    private void cargarClienteForm() {
        int fila = this.tableClientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente ", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tableClientes.getModel();
            int idCliente = (int) modelo.getValueAt(fila, 0);
            Cliente cliente = controlCliente.consultarCliente(idCliente);
            if (cliente != null) {
                txtID.setText(String.valueOf(cliente.getId()));
                txtRFC.setText(cliente.getRfc());
                txtNombre.setText(cliente.getNombre());
                txtDireccion.setText(cliente.getDireccion());
                txtTelefono1.setText(cliente.getTelefono1());
                txtTelefono2.setText(cliente.getTelefono2());
            }
        }
    }

    private void cargarClientes() {
        List<Cliente> clientes = this.controlCliente.consultarClientes(txtBuscar.getText());
        if (clientes != null) {
            DefaultTableModel modelo = (DefaultTableModel) tableClientes.getModel();
            modelo.setRowCount(0);
            for (Cliente cliente : clientes) {
                modelo.addRow(cliente.toArray());
            }
        }
    }

    private void insertarCliente() {
        if (txtID.getText().equals("") && !txtRFC.getText().equals("") && !txtNombre.getText().equals("") && !txtDireccion.getText().equals("")) {
            Cliente cliente = new Cliente();
            cliente.setRfc(txtRFC.getText());
            cliente.setNombre(txtNombre.getText());
            cliente.setDireccion(txtDireccion.getText());
            cliente.setTelefono1(txtTelefono1.getText());
            cliente.setTelefono2(txtTelefono2.getText());
            this.controlCliente.insertarCliente(cliente);
        }
    }

    private void actualizarCliente() {
        if (!txtID.getText().equals("") && !txtRFC.getText().equals("") && !txtNombre.getText().equals("") && !txtDireccion.getText().equals("")) {
            Cliente cliente = new Cliente();
            cliente.setId(Integer.parseInt(txtID.getText()));
            cliente.setRfc(txtRFC.getText());
            cliente.setNombre(txtNombre.getText());
            cliente.setDireccion(txtDireccion.getText());
            cliente.setTelefono1(txtTelefono1.getText());
            cliente.setTelefono2(txtTelefono2.getText());
            this.controlCliente.actualizarCliente(cliente);
        }

    }

    private void eliminarCliente() {
        int fila = tableClientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente ", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tableClientes.getModel();
            Integer idCliente = (Integer) modelo.getValueAt(fila, 0);
            boolean eliminado = this.controlCliente.eliminarCliente(idCliente);
            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Se elimino el cliente correctamente!", "Eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el cliente", "Eliminación fallida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void limpiarFormulario() {
        txtID.setText("");
        txtRFC.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono1.setText("");
        txtTelefono2.setText("");
        txtBuscar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JMenuItem busquedaVentaOption;
    private javax.swing.JMenuItem categoriasOption;
    private javax.swing.JMenuItem clientesOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblTablaClientes;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    private java.awt.ScrollPane paneClientes;
    private javax.swing.JMenuItem productosOption;
    private javax.swing.JMenuItem provedoresOption;
    private javax.swing.JMenuItem registrarVentaOption;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
